version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jira

  jira:
    image: 276003551821.dkr.ecr.eu-central-1.amazonaws.com/kotlin-jira-client:1
    network_mode: host
    environment:
      - CATALINA_OPTS=-Xmx3072m -Xms3072m