name: Development (Build & Test)
on:
  push:
    tags-ignore:
      - '*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-kotlin-jira-client-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-kotlin-jira-client-

      - name: Configure aws ecr credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login aws ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Startup Jira and Insight
        run: docker-compose up -d

      - name: Wait for Jira and Insight
        run: ./scripts/waitingForJira.sh

      - name: Build library
        run: ./gradlew clean install --info

      - name: Integration test for ktor
        run: ./gradlew test --info

      - name: Integration test for confluence
        run: |
          NEW_VERSION=$(./gradlew cV | grep "Project version" | cut -d ":" -f2 | xargs | awk '{print $1}') 
          echo "mvn building version: ${NEW_VERSION}"
          mvn clean -f kotlin-jira-client-atlas-test/pom.xml -B verify -Pci -Dlibrary.version=${NEW_VERSION}
